stella:
  start: stella/start.sh
  dockerfile: stella/Dockerfile
  kwargs_type: argparse
  kwargs:
    model: ${{ env.OPENROUTER_MODEL }}
    max_tools: ${{ env.BMLB_STEP_LIMIT }}
    timeout_seconds: ${{ env.BMLB_TIME_LIMIT_SECS }}
    use_templates: true
    # Note: use_templates and use_mem0 are boolean flags (True/False)
    # Enabling templates activates STELLA's iterative workflow with critic agent
  env_vars:
    TIME_LIMIT_SECS: ${{ env.BMLB_TIME_LIMIT_SECS }}
    STEP_LIMIT: ${{ env.BMLB_STEP_LIMIT }}
    OPENROUTER_API_KEY: ${{ env.OPENROUTER_API_KEY }}
    OPENROUTER_BASE_URL: ${{ env.OPENROUTER_BASE_URL }}
    OPENROUTER_MODEL: ${{ env.OPENROUTER_MODEL }}
